Due to deprecated warning when trying to import use correct method for Rails 4.x
Error: "NoMethodError: undefined method `find_or_initialize_by_name'"